import { test, expect, chromium, type BrowserContext, type Page } from '@playwright/test';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { createServer, type Server } from 'node:http';
import { join, resolve } from 'node:path';

test.describe.configure({ mode: 'serial' });
let context: BrowserContext;
let profile: string;
let base: string;
let library: Page;
let modelServer: Server;
let modelEndpoint: string;
const modelRequests: string[] = [];
const errors: string[] = [];
const articleUrl = 'https://github.com/starts-fixture/article/issues/1?utm_source=test';
const articleText = '在 Cloudflare Workers 上使用 SQLite 保存数据。终端界面开发可以结合 TypeScript 和本地检索，让开发工具更加易用。';

async function closeDialog(page: Page) { await page.getByRole('button', { name: '关闭弹窗', exact: true }).last().click(); }
async function noOverflow(page: Page) { expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); }

test.beforeAll(async () => {
  modelServer = createServer(async (request, response) => {
    let body = ''; for await (const chunk of request) body += chunk;
    modelRequests.push(body);
    response.writeHead(200, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' });
    response.end(JSON.stringify({ choices: [{ message: { content: JSON.stringify({ summary: '用于终端开发的 TypeScript UI 组件。', category: '终端工具', tags: ['终端'], keywords: ['命令行'], stack: ['TypeScript'], useCases: ['开发命令行'] }) } }] }));
  });
  await new Promise<void>(ready => modelServer.listen(0, '127.0.0.1', ready));
  const address = modelServer.address(); if (!address || typeof address === 'string') throw new Error('No model port');
  modelEndpoint = `http://127.0.0.1:${address.port}/v1`;
  profile = await mkdtemp(join(tmpdir(), 'starts-browser-'));
  const extension = resolve('.output/chrome-mv3');
  context = await chromium.launchPersistentContext(profile, {
    channel: 'chromium', locale: 'zh-CN', headless: true, viewport: { width: 1440, height: 1000 },
    args: ['--no-proxy-server', '--enable-unsafe-extension-debugging', `--disable-extensions-except=${extension}`, `--load-extension=${extension}`],
  });
  context.on('page', page => page.on('pageerror', error => errors.push(error.message)));
  await context.route('https://github.com/starts-fixture/**', async route => {
    const url = new URL(route.request().url());
    const repo = url.pathname === '/starts-fixture/terminal';
    const docs = url.pathname.includes('/docs/');
    await route.fulfill({ contentType: 'text/html; charset=utf-8', body: `<!doctype html><html lang="zh-CN"><head><title>${repo ? 'Terminal Kit' : docs ? 'Workers 文档' : 'Workers SQLite 实践'}</title><meta name="description" content="Workers 与 SQLite 的开发实践"><meta name="keywords" content="Workers,SQLite,终端"><meta name="author" content="Fixture"></head><body>${repo ? '<div id="repository-container-header"><h1>starts-fixture/terminal</h1><ul class="pagehead-actions" style="display:flex;list-style:none;gap:8px"><li><button type="button" class="btn btn-sm">Fork</button></li><li><form action="/starts-fixture/terminal/star"><button type="submit" class="btn btn-sm" aria-label="Star this repository">Star</button></form></li></ul></div>' : ''}<article><h1>${docs ? 'Workers 文档' : 'Workers SQLite 实践'}</h1>${Array.from({ length: 10 }, () => `<p>${articleText}</p>`).join('')}</article></body></html>` });
  });
  await context.route('https://api.github.com/repos/starts-fixture/**', async route => {
    const readme = route.request().url().endsWith('/readme');
    await route.fulfill({ json: readme ? { encoding: 'base64', content: Buffer.from('# Terminal Kit\nTypeScript terminal UI library. 中文终端界面组件。').toString('base64') } : { id: 123456, private: false, description: 'TypeScript terminal UI library', language: 'TypeScript', topics: ['terminal', 'cli'], license: { spdx_id: 'MIT' }, stargazers_count: 2026 } });
  });
  const worker = context.serviceWorkers()[0] ?? await context.waitForEvent('serviceworker');
  base = `chrome-extension://${new URL(worker.url()).hostname}`;
  library = await context.newPage();
  await library.goto(`${base}/library.html`);
});

test.afterAll(async () => { await context?.close(); if (modelServer) { modelServer.closeAllConnections(); await new Promise<void>(done => modelServer.close(() => done())); } if (profile) await rm(profile, { recursive: true, force: true }); });

test('capture, edit, search and shared-state flows on desktop and mobile', async () => {
  await expect(library.getByText('还没有收藏', { exact: true })).toBeVisible();
  await noOverflow(library);
  await library.screenshot({ animations: 'disabled', path: 'test-results/library-empty-desktop.png', fullPage: true });
  const article = await context.newPage();
  await article.goto(articleUrl);
  await article.locator('article p').first().evaluate(node => { const range = document.createRange(); range.selectNodeContents(node); const selection = window.getSelection(); selection?.removeAllRanges(); selection?.addRange(range); });
  await library.getByRole('button', { name: '保存当前页', exact: true }).click();
  await expect(library.getByRole('button', { name: '查看详情：Workers SQLite 实践' })).toBeVisible();
  await library.getByRole('button', { name: '查看详情：Workers SQLite 实践' }).click();
  await library.getByRole('tab', { name: '正文', exact: true }).click();
  await expect(library.locator('.content-text')).toContainText(articleText);
  await library.getByRole('tab', { name: '笔记与划词', exact: true }).click();
  await expect(library.locator('blockquote')).toContainText(articleText);
  await library.getByRole('button', { name: '编辑', exact: true }).click();
  await library.getByLabel('标题', { exact: true }).fill('边缘数据库实践');
  await library.getByLabel('简介', { exact: false }).fill('人工整理：边缘存储');
  await library.getByLabel('标签', { exact: true }).fill('数据库, Workers');
  await library.getByLabel('分类', { exact: true }).fill('开发笔记');
  await library.getByLabel('私人笔记', { exact: false }).fill('PRIVATE-NOTE：项目选型时使用');
  await library.getByRole('button', { name: '保存修改', exact: true }).click();
  await closeDialog(library);
  const sidepanel = await context.newPage();
  await sidepanel.goto(`${base}/sidepanel.html`);
  await sidepanel.setViewportSize({ width: 390, height: 844 });
  await expect(sidepanel.getByRole('button', { name: '查看详情：边缘数据库实践' })).toBeVisible();
  await sidepanel.getByRole('searchbox', { name: '搜索收藏' }).fill('项目选型');
  await expect(sidepanel.getByRole('button', { name: '查看详情：边缘数据库实践' })).toBeVisible();
  await sidepanel.getByRole('searchbox', { name: '搜索收藏' }).fill('没有这个词');
  await expect(sidepanel.getByText('暂时没有找到')).toBeVisible();
  await sidepanel.getByRole('button', { name: '清除搜索与筛选' }).click();
  await noOverflow(sidepanel);
  await sidepanel.screenshot({ animations: 'disabled', path: 'test-results/sidepanel-mobile.png', fullPage: true });
  await article.bringToFront();
  await library.getByRole('button', { name: '保存当前页', exact: true }).click();
  await expect(library.getByText('此页面已在资料库中，已保留你的笔记。')).toBeVisible();
  await expect(library.locator('.item-list > li')).toHaveCount(1);
  const repo = await context.newPage();
  await repo.goto('https://github.com/starts-fixture/terminal');
  const githubSave = repo.getByRole('button', { name: '收藏 terminal 到 WebsiteStars' });
  await expect(githubSave).toBeVisible();
  expect(await githubSave.evaluate(node => {
    const slot = node.closest('[data-starts-slot]');
    return slot?.parentElement?.classList.contains('pagehead-actions') && !!slot.previousElementSibling?.querySelector('form[action$="/star"]') && !node.closest('form');
  })).toBe(true);
  await githubSave.click();
  await expect(repo.getByRole('button', { name: '收藏 terminal 到 WebsiteStars' })).toHaveText('已收藏到 WebsiteStars');
  await expect(library.locator('.item-list > li')).toHaveCount(2);
  await library.getByRole('tab', { name: /GitHub/ }).click();
  await expect(library.locator('.item-list > li')).toHaveCount(1);
  await library.getByRole('button', { name: '查看详情：starts-fixture/terminal' }).click();
  await expect(library.getByText('TypeScript', { exact: true }).last()).toBeVisible();
  await library.getByRole('tab', { name: 'README', exact: true }).click();
  await expect(library.locator('.content-text')).toContainText('Terminal Kit');
  await library.getByRole('button', { name: '刷新仓库', exact: true }).click();
  await expect(library.getByText('仓库信息已刷新，私人笔记和人工编辑已保留。')).toBeVisible();
  await library.getByRole('tab', { name: '概览', exact: true }).click();
  await library.getByRole('button', { name: '配置 AI 分析', exact: true }).click();
  await expect(library.getByRole('button', { name: '前往 AI 设置' })).toBeVisible();
  await closeDialog(library);
  await library.getByRole('tab', { name: /^全部/ }).click();
  await library.setViewportSize({ width: 390, height: 844 });
  await library.getByRole('button', { name: '展开筛选条件' }).click();
  await library.getByLabel('按标签筛选', { exact: true }).selectOption('数据库');
  await expect(library.locator('.item-list > li')).toHaveCount(1);
  await library.getByLabel('按分类筛选').selectOption('开发笔记');
  await expect(library.locator('.item-list > li')).toHaveCount(1);
  await library.getByRole('button', { name: '清除筛选', exact: true }).click();
  await library.setViewportSize({ width: 1440, height: 1000 });
  await library.screenshot({ animations: 'disabled', path: 'test-results/library-desktop.png', fullPage: true });
  await library.setViewportSize({ width: 390, height: 844 });
  await noOverflow(library);
  await library.getByRole('button', { name: '查看详情：边缘数据库实践' }).click();
  await noOverflow(library);
  await library.screenshot({ animations: 'disabled', path: 'test-results/detail-mobile.png', fullPage: true });
  await closeDialog(library);
  await library.setViewportSize({ width: 1440, height: 1000 });
  await sidepanel.close(); await repo.close(); await article.close();
  expect(errors).toEqual([]);
});

test('settings, backups, invalid imports and deletion stay consistent across pages', async () => {
  const options = await context.newPage();
  await options.goto(`${base}/options.html`);
  await expect(options.getByRole('switch', { name: '启用 AI 分析' })).not.toBeChecked();
  await options.getByLabel('GitHub Token（可选）', { exact: false }).fill('LOCAL-SECRET-DO-NOT-EXPORT');
  await options.getByLabel('禁止分析的域名', { exact: false }).fill('private.example.com');
  await options.getByRole('button', { name: '保存设置', exact: true }).click();
  await expect(options.getByText('设置已保存，AI 已关闭。本地收藏与搜索照常可用。')).toBeVisible();
  await options.reload();
  await expect(options.getByLabel('GitHub Token（可选）', { exact: false })).toHaveValue('LOCAL-SECRET-DO-NOT-EXPORT');
  await noOverflow(options);
  await options.screenshot({ animations: 'disabled', path: 'test-results/options-desktop.png', fullPage: true });
  const downloadPromise = options.waitForEvent('download');
  await options.getByRole('button', { name: '导出 JSON', exact: true }).click();
  const download = await downloadPromise;
  const backup = await readFile((await download.path())!, 'utf8');
  expect(backup).not.toContain('LOCAL-SECRET');
  expect(backup).toContain('PRIVATE-NOTE');
  expect(JSON.parse(backup).items).toHaveLength(2);
  await library.getByRole('button', { name: '查看详情：边缘数据库实践' }).click();
  await library.getByRole('button', { name: '删除收藏', exact: true }).click();
  await library.getByRole('button', { name: '保留收藏', exact: true }).click();
  await expect(library.getByRole('heading', { name: '边缘数据库实践' })).toBeVisible();
  await library.getByRole('button', { name: '删除收藏', exact: true }).click();
  await library.getByRole('button', { name: '确认删除', exact: true }).click();
  await expect(library.locator('.item-list > li')).toHaveCount(1);
  await options.getByLabel('选择 JSON 备份文件').setInputFiles({ name: 'backup.json', mimeType: 'application/json', buffer: Buffer.from(backup) });
  await expect(options.getByRole('dialog', { name: '确认导入备份' })).toBeVisible();
  await options.getByRole('button', { name: '确认导入 2 条', exact: true }).click();
  await expect(options.getByText('导入完成：新增 1 条，跳过 1 条重复收藏。')).toBeVisible();
  await expect(library.locator('.item-list > li')).toHaveCount(2);
  await library.getByRole('button', { name: '查看详情：边缘数据库实践' }).click();
  await library.getByRole('tab', { name: '笔记与划词', exact: true }).click();
  await expect(library.getByText('PRIVATE-NOTE：项目选型时使用', { exact: true })).toBeVisible();
  await closeDialog(library);
  const malicious = JSON.parse(backup); malicious.items[0].url = 'javascript:alert(1)';
  await options.getByLabel('选择 JSON 备份文件').setInputFiles({ name: 'invalid.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(malicious)) });
  await expect(options.getByText(/无法读取备份/)).toBeVisible();
  await expect(library.locator('.item-list > li')).toHaveCount(2);
  await options.locator('label').filter({ has: options.getByRole('switch', { name: '启用 AI 分析', exact: true }) }).click();
  await options.getByLabel('服务地址', { exact: true }).fill('http://insecure.example.com/v1');
  await options.getByLabel('API Key', { exact: true }).fill('fake-key');
  await options.getByRole('button', { name: '保存设置', exact: true }).click();
  await expect(options.getByText('AI 服务地址须使用 HTTPS；仅本机 loopback 地址允许 HTTP。')).toBeVisible();
  await options.locator('label').filter({ has: options.getByRole('switch', { name: '启用 AI 分析', exact: true }) }).click();
  await options.getByLabel('服务地址', { exact: true }).fill('https://api.x.ai/v1');
  await options.getByLabel('API Key', { exact: true }).fill('');
  await options.getByLabel('GitHub Token（可选）', { exact: false }).fill('');
  await options.getByRole('button', { name: '保存设置', exact: true }).click();
  await expect(options.getByText('设置已保存，AI 已关闭。本地收藏与搜索照常可用。')).toBeVisible();
  await options.setViewportSize({ width: 390, height: 844 });
  await noOverflow(options);
  await options.screenshot({ animations: 'disabled', path: 'test-results/options-mobile.png', fullPage: true });
  await options.locator('label').filter({ has: options.getByRole('radio', { name: /Workers AI/ }) }).click();
  await expect(options.getByLabel('Cloudflare Account ID', { exact: false })).toBeVisible();
  await expect(options.getByLabel('模型', { exact: true })).toHaveValue('@cf/meta/llama-3.1-8b-instruct');
  await options.getByRole('button', { name: '保存设置', exact: true }).click();
  await expect(options.getByText('设置已保存，AI 已关闭。本地收藏与搜索照常可用。')).toBeVisible();
  await library.reload();
  await expect(library.locator('.item-list > li')).toHaveCount(2);
  expect(errors).toEqual([]);
  await options.close();
});

test('manual add, extraction upgrades, documents and configured AI', async () => {
  await library.getByRole('button', { name: '添加链接', exact: true }).click();
  await library.getByLabel('链接', { exact: false }).fill('javascript:alert(1)');
  await library.getByRole('button', { name: '添加收藏', exact: true }).click();
  await expect(library.getByText('请输入完整的 http(s) 链接，或 GitHub 的 owner/repo。')).toBeVisible();
  const docsUrl = 'https://github.com/starts-fixture/docs/wiki/Intro';
  await library.getByLabel('链接', { exact: false }).fill(docsUrl);
  await library.getByLabel('标题（可选）').fill('技术文档手动收藏');
  await library.getByRole('button', { name: '添加收藏', exact: true }).click();
  await expect(library.getByRole('heading', { name: '技术文档手动收藏' })).toBeVisible();
  await closeDialog(library);
  const docs = await context.newPage();
  await docs.goto(docsUrl);
  await library.getByRole('button', { name: '保存当前页', exact: true }).click();
  await library.getByRole('tab', { name: /文档/ }).click();
  await expect(library.locator('.item-list > li')).toHaveCount(1);
  await library.getByRole('button', { name: '查看详情：技术文档手动收藏' }).click();
  await library.getByRole('tab', { name: '正文', exact: true }).click();
  await expect(library.locator('.content-text')).toContainText(articleText);
  await closeDialog(library);
  await library.getByRole('tab', { name: /^全部/ }).click();
  const requests = modelRequests;
  const options = await context.newPage();
  await options.goto(`${base}/options.html`);
  await options.locator('label').filter({ has: options.getByRole('radio', { name: /兼容端点/ }) }).click();
  await options.getByLabel('服务地址', { exact: true }).fill(modelEndpoint);
  await options.getByLabel('API Key', { exact: true }).fill('test-key');
  await options.locator('label').filter({ has: options.getByRole('switch', { name: '启用 AI 分析', exact: true }) }).click();
  await options.getByRole('button', { name: '保存设置', exact: true }).click();
  await expect(options.getByText('设置已保存。仅在收藏或主动分析时使用 AI，未发送测试内容。')).toBeVisible();
  expect(requests).toHaveLength(0);
  await library.getByRole('button', { name: '查看详情：边缘数据库实践' }).click();
  await library.getByRole('button', { name: /配置 AI 分析|重新分析/, exact: true }).click();
  await expect(library.getByText('已完成分析', { exact: true })).toBeVisible();
  await expect(library.getByRole('dialog').getByText('人工整理：边缘存储', { exact: true })).toBeVisible();
  expect(requests).toHaveLength(1);
  expect(requests[0]).not.toContain('PRIVATE-NOTE');
  expect(requests[0]).not.toContain('项目选型');
  await closeDialog(library);
  await library.getByRole('searchbox', { name: '搜索收藏' }).fill('命令行');
  await expect(library.getByRole('button', { name: '查看详情：边缘数据库实践' })).toBeVisible();
  await library.getByRole('button', { name: '清空搜索' }).click();
  await options.locator('label').filter({ has: options.getByRole('switch', { name: '启用 AI 分析', exact: true }) }).click();
  await options.getByRole('button', { name: '保存设置', exact: true }).click();
  await expect(options.getByText('设置已保存，AI 已关闭。本地收藏与搜索照常可用。')).toBeVisible();
  await options.close(); await docs.close();
  expect(errors).toEqual([]);
});

test('opening the sidebar and refreshing never saves a page; explicit capture still works', async () => {
  const page = await context.newPage();
  await context.route('https://starts-fixture.example/**', route => route.fulfill({ contentType: 'text/html; charset=utf-8', body: `<!doctype html><meta charset="utf-8"><title>普通网站的工具栏收藏</title><article><h1>普通网站的工具栏收藏</h1>${Array.from({ length: 8 }, () => `<p>${articleText}</p>`).join('')}</article>` }));
  await page.goto('https://starts-fixture.example/article');
  const count = await library.locator('.item-list > li').count();
  const session = await context.browser()!.newBrowserCDPSession();
  const { targetInfos } = await session.send('Target.getTargets', { filter: [{ type: 'tab' }] });
  const target = targetInfos.find(info => info.url === page.url());
  expect(target).toBeDefined();
  await session.send('Extensions.triggerAction', { id: new URL(base).hostname, targetId: target!.targetId });
  await expect.poll(async () => (await session.send('Target.getTargets')).targetInfos.some(info => info.url === `${base}/sidepanel.html`)).toBe(true);
  await library.getByRole('button', { name: '刷新资料库', exact: true }).click();
  await expect(library.getByRole('status').filter({ hasText: '已刷新' })).toBeVisible();
  await expect(library.locator('.item-list > li')).toHaveCount(count);
  await expect(library.getByRole('button', { name: '查看详情：普通网站的工具栏收藏' })).toHaveCount(0);
  await session.send('Extensions.triggerAction', { id: new URL(base).hostname, targetId: target!.targetId });
  const sidebar = await context.newPage(); await sidebar.goto(`${base}/sidepanel.html`);
  await sidebar.setViewportSize({ width: 390, height: 844 });
  await expect(sidebar.locator('.item-list > li')).toHaveCount(count);
  await sidebar.getByRole('searchbox', { name: '搜索收藏' }).fill('边缘数据库');
  await sidebar.getByRole('tab', { name: /文章/ }).click();
  await sidebar.getByLabel('排序方式').selectOption('name');
  await sidebar.getByRole('button', { name: '刷新资料库', exact: true }).click();
  await expect(sidebar.getByRole('status').filter({ hasText: '已刷新' })).toBeVisible();
  await expect(sidebar.getByRole('searchbox', { name: '搜索收藏' })).toHaveValue('边缘数据库');
  await expect(sidebar.getByRole('tab', { name: /文章/ })).toHaveAttribute('aria-selected', 'true');
  await expect(sidebar.getByLabel('排序方式')).toHaveValue('name');
  await expect(sidebar.locator('.item-list > li')).toHaveCount(1);
  await expect(library.locator('.item-list > li')).toHaveCount(count);
  await sidebar.getByRole('button', { name: '清空搜索' }).click();
  await sidebar.getByRole('tab', { name: /^全部/ }).click();
  await page.bringToFront();
  await sidebar.getByRole('button', { name: '保存当前页', exact: true }).click();
  await expect(sidebar.getByRole('button', { name: '查看详情：普通网站的工具栏收藏' })).toBeVisible();
  await expect(library.locator('.item-list > li')).toHaveCount(count + 1);
  await sidebar.getByRole('button', { name: '刷新资料库', exact: true }).click();
  await expect(sidebar.getByRole('status').filter({ hasText: '已刷新' })).toBeVisible();
  await expect(library.locator('.item-list > li')).toHaveCount(count + 1);
  await noOverflow(sidebar);
  await sidebar.screenshot({ animations: 'disabled', path: 'test-results/sidebar-refresh-mobile.png', fullPage: true });
  await library.getByRole('button', { name: '查看详情：普通网站的工具栏收藏' }).click();
  await library.getByRole('tab', { name: '正文', exact: true }).click();
  await expect(library.locator('.content-text')).toContainText(articleText);
  await closeDialog(library);
  await session.detach(); await sidebar.close(); await page.close();
  expect(errors).toEqual([]);
});

test('stale settings cannot restore removed credentials and Stars buttons deduplicate', async () => {
  const first = await context.newPage();
  const stale = await context.newPage();
  await first.goto(`${base}/options.html`);
  await stale.goto(`${base}/options.html`);
  await expect(stale.getByRole('switch', { name: '启用 AI 分析' })).not.toBeChecked();
  await first.getByLabel('API Key', { exact: true }).fill('');
  await first.getByLabel('禁止分析的域名', { exact: true }).fill('private.example.com\nstarts-fixture.example');
  await first.getByRole('button', { name: '保存设置', exact: true }).click();
  await expect(first.getByText('设置已保存，AI 已关闭。本地收藏与搜索照常可用。')).toBeVisible();
  await stale.locator('label').filter({ has: stale.getByRole('switch', { name: '保留正文 / README', exact: true }) }).click();
  await stale.getByRole('button', { name: '保存设置', exact: true }).click();
  await expect(stale.getByText('设置已在其他页面更新，请重新加载后再保存。')).toBeVisible();
  await first.reload();
  await expect(first.getByLabel('API Key', { exact: true })).toHaveValue('');
  await expect(first.getByRole('switch', { name: '保留正文 / README' })).toBeChecked();
  await first.close(); await stale.close();
  await context.route('https://github.com/starts-fixture?tab=stars', route => route.fulfill({ contentType: 'text/html; charset=utf-8', body: '<!doctype html><title>Stars</title><main><div class="col-12"><div class="float-right"><form action="/starts-fixture/terminal/unstar"><button type="submit" class="btn btn-sm" aria-label="Unstar this repository">Starred</button></form></div><div><h3><a href="/starts-fixture/terminal">terminal</a></h3></div></div></main>' }));
  const stars = await context.newPage();
  await stars.goto('https://github.com/starts-fixture?tab=stars');
  const count = await library.locator('.item-list > li').count();
  await stars.getByRole('button', { name: '收藏 terminal 到 WebsiteStars' }).click();
  await expect(stars.getByRole('button', { name: '收藏 terminal 到 WebsiteStars' })).toHaveText('已收藏到 WebsiteStars');
  await expect(library.locator('.item-list > li')).toHaveCount(count);
  await stars.close();
  expect(errors).toEqual([]);
});

test('queued repository enrichment survives a real service-worker restart', async () => {
  let firstRequestStarted = false;
  await context.route('https://api.github.com/repos/starts-fixture/restart-slow', async route => {
    firstRequestStarted = true;
    await new Promise<void>(resolve => { releaseSlow = resolve; });
    await route.abort().catch(() => undefined);
  });
  let releaseSlow: (() => void) | undefined;
  const protocol = await context.newCDPSession(library);
  const versions = new Map<string, { versionId: string; scriptURL: string; runningStatus: string }>();
  protocol.on('ServiceWorker.workerVersionUpdated', event => { for (const version of event.versions) versions.set(version.versionId, version); });
  await protocol.send('ServiceWorker.enable');
  async function addRepository(name: string) {
    await library.getByRole('button', { name: '添加链接', exact: true }).click();
    await library.getByLabel('链接', { exact: true }).fill(`starts-fixture/${name}`);
    await library.getByRole('button', { name: '添加收藏', exact: true }).click();
    await expect(library.getByRole('heading', { name: `starts-fixture/${name}`, exact: true })).toBeVisible();
    await closeDialog(library);
  }
  try {
    await addRepository('restart-slow');
    await expect.poll(() => firstRequestStarted).toBe(true);
    await addRepository('restart-pending');
    await expect.poll(() => [...versions.values()].some(version => version.scriptURL.startsWith(base) && version.runningStatus === 'running')).toBe(true);
    const worker = [...versions.values()].find(version => version.scriptURL.startsWith(base) && version.runningStatus === 'running')!;
    await protocol.send('ServiceWorker.stopWorker', { versionId: worker.versionId });
    releaseSlow?.();
    const options = await context.newPage();
    await options.goto(`${base}/options.html`);
    await expect(options.getByRole('switch', { name: '启用 AI 分析' })).not.toBeChecked();
    await library.getByRole('button', { name: '查看详情：starts-fixture/restart-pending' }).click();
    await expect(library.getByRole('dialog').getByText('TypeScript', { exact: true })).toBeVisible();
    await library.getByRole('tab', { name: 'README', exact: true }).click();
    await expect(library.locator('.content-text')).toContainText('Terminal Kit');
    await closeDialog(library); await options.close();
  } finally { releaseSlow?.(); await protocol.detach(); }
  expect(errors).toEqual([]);
});
