import { test, expect, chromium } from '@playwright/test';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';

const paragraph = '使用浏览器扩展整理开发资料。这个页面讨论中文全文检索、TypeScript 工具与离线阅读，只有用户点击收藏时才提取正文。';

test('floating capture is isolated, user initiated, responds to navigation and can be disabled everywhere', async () => {
  const profile = await mkdtemp(join(tmpdir(), 'starts-floating-'));
  const extension = resolve('.output/chrome-mv3');
  const context = await chromium.launchPersistentContext(profile, {
    channel: 'chromium', locale: 'zh-CN', headless: true, hasTouch: true, viewport: { width: 1360, height: 900 },
    args: [`--disable-extensions-except=${extension}`, `--load-extension=${extension}`],
  });
  const errors: string[] = [];
  context.on('page', page => page.on('pageerror', error => errors.push(error.message)));
  try {
    await context.route('https://floating.example/**', route => route.fulfill({
      contentType: 'text/html; charset=utf-8',
      body: `<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>悬浮收藏测试文章</title><meta name="description" content="从网页直接保存正文与划词"><style>body{font:16px/1.8 system-ui;margin:0;background:#fafafa;color:#18181b}main{max-width:720px;margin:40px auto;padding:20px}button{width:100%!important;background:red!important;font-size:40px!important}input{display:block}h1{font-size:30px}</style><main><article><h1>悬浮收藏测试文章</h1>${Array.from({ length: 10 }, () => `<p>${paragraph}</p>`).join('')}</article><form><input value="DO-NOT-CAPTURE-PASSWORD" type="password"><textarea>DO-NOT-CAPTURE-DRAFT</textarea></form></main></html>`,
    }));
    const worker = context.serviceWorkers()[0] ?? await context.waitForEvent('serviceworker');
    const base = `chrome-extension://${new URL(worker.url()).hostname}`;
    const library = await context.newPage(); await library.goto(`${base}/library.html`);
    const page = await context.newPage(); await page.goto('https://floating.example/article');
    const save = page.getByRole('button', { name: '收藏当前网页到 WebsiteStars', exact: true });
    await expect(save).toBeVisible();
    await expect(library.locator('.item-list > li')).toHaveCount(0);
    expect((await save.boundingBox())?.width).toBe(44);
    await expect(save).toHaveCSS('background-color', 'rgb(37, 99, 235)');
    const initial = (await save.boundingBox())!;
    await page.mouse.move(initial.x + 22, initial.y + 22);
    await page.mouse.down();
    await page.mouse.move(340, 260, { steps: 12 });
    await page.mouse.up();
    await expect.poll(async () => Math.round((await save.boundingBox())!.x)).toBe(318);
    await expect.poll(async () => Math.round((await save.boundingBox())!.y)).toBe(238);
    await library.getByRole('button', { name: '刷新资料库' }).click();
    await expect(library.getByRole('status').filter({ hasText: '已刷新' })).toBeVisible();
    await expect(library.locator('.item-list > li')).toHaveCount(0);
    await page.getByRole('button', { name: '收起到侧边' }).click();
    const expand = page.getByRole('button', { name: '展开收藏按钮' });
    await expect(expand).toBeVisible(); await expect(save).toBeHidden();
    expect((await expand.boundingBox())!.x).toBe(0);
    await page.screenshot({ animations: 'disabled', path: 'test-results/floating-collapsed-left.png' });
    await expand.click(); await expect(save).toBeVisible();
    expect((await save.boundingBox())!.x).toBe(16);
    await expect(library.locator('.item-list > li')).toHaveCount(0);
    const left = (await save.boundingBox())!;
    await page.mouse.move(left.x + 22, left.y + 22); await page.mouse.down();
    await page.mouse.move(1356, 210, { steps: 12 }); await page.mouse.up();
    expect((await save.boundingBox())!.x).toBe(1300);
    await page.getByRole('button', { name: '收起到侧边' }).click();
    await expect(expand).toBeVisible();
    expect((await expand.boundingBox())!.x).toBe(1338);
    await expand.focus(); await page.keyboard.press('Enter');
    await expect(save).toBeVisible();
    await page.keyboard.press('Alt+ArrowLeft');
    expect((await save.boundingBox())!.x).toBe(1284);
    await expect(library.locator('.item-list > li')).toHaveCount(0);
    await page.evaluate(() => document.documentElement.requestFullscreen());
    await expect(save).toHaveCount(0);
    await page.evaluate(() => document.exitFullscreen());
    await expect(save).toBeVisible();
    await expect(library.locator('.item-list > li')).toHaveCount(0);
    await page.locator('article p').first().evaluate(node => {
      const range = document.createRange(); range.selectNodeContents(node);
      const selection = window.getSelection(); selection?.removeAllRanges(); selection?.addRange(range);
    });
    await save.click();
    await expect(page.getByRole('status')).toContainText('已收藏到 WebsiteStars');
    await expect(library.getByRole('button', { name: '查看详情：悬浮收藏测试文章' })).toBeVisible();
    await save.click();
    await expect(page.getByRole('status')).toContainText('已在资料库中');
    await expect(library.locator('.item-list > li')).toHaveCount(1);
    await library.getByRole('button', { name: '查看详情：悬浮收藏测试文章' }).click();
    await library.getByRole('tab', { name: '正文', exact: true }).click();
    await expect(library.locator('.content-text')).toContainText(paragraph);
    await expect(library.locator('.content-text')).not.toContainText('DO-NOT-CAPTURE');
    await library.getByRole('tab', { name: '笔记与划词', exact: true }).click();
    await expect(library.locator('blockquote')).toContainText(paragraph);
    await library.getByRole('button', { name: '关闭弹窗' }).last().click();
    await page.screenshot({ animations: 'disabled', path: 'test-results/floating-desktop.png', fullPage: false });
    await page.evaluate(() => { history.pushState({}, '', '/second'); document.title = '第二篇悬浮测试文章'; });
    await expect(save).not.toHaveAttribute('data-saved');
    await save.click();
    await expect(library.locator('.item-list > li')).toHaveCount(2);
    await page.setViewportSize({ width: 390, height: 844 });
    await expect(save).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ animations: 'disabled', path: 'test-results/floating-mobile.png', fullPage: false });
    await page.emulateMedia({ colorScheme: 'dark' });
    await page.mouse.move(100, 100);
    await expect(save).toHaveCSS('background-color', 'rgb(21, 128, 61)');
    await expect(save).toHaveCSS('color', 'rgb(255, 255, 255)');
    await page.screenshot({ animations: 'disabled', path: 'test-results/floating-mobile-dark.png', fullPage: false });
    const touch = await context.newCDPSession(page);
    const beforeTouch = (await save.boundingBox())!;
    await touch.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: beforeTouch.x + 22, y: beforeTouch.y + 22 }] });
    await touch.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: 110, y: 380 }] });
    await touch.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
    await expect.poll(async () => Math.round((await save.boundingBox())!.x)).toBe(88);
    await expect.poll(async () => Math.round((await save.boundingBox())!.y)).toBe(358);
    await expect(library.locator('.item-list > li')).toHaveCount(2);
    await touch.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: 110, y: 380 }] });
    await touch.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: 150, y: 420 }] });
    await touch.send('Input.dispatchTouchEvent', { type: 'touchCancel', touchPoints: [] });
    await expect(save).not.toHaveAttribute('data-dragging');
    await expect(library.locator('.item-list > li')).toHaveCount(2);
    await touch.detach();
    await page.getByRole('button', { name: '收起到侧边' }).click();
    await expect(expand).toBeVisible(); await expect(save).toBeHidden();
    await page.setViewportSize({ width: 320, height: 568 });
    const handle = (await expand.boundingBox())!;
    expect(handle.x).toBeGreaterThanOrEqual(0);
    expect(handle.x + handle.width).toBeLessThanOrEqual(320);
    expect(handle.y + handle.height).toBeLessThanOrEqual(568);
    await page.screenshot({ animations: 'disabled', path: 'test-results/floating-collapsed-mobile.png' });
    await expand.focus(); await page.keyboard.press('Space');
    await expect(save).toBeVisible();
    await expect(library.locator('.item-list > li')).toHaveCount(2);
    await page.reload(); await expect(save).toBeVisible();
    const other = await context.newPage(); await other.goto('https://floating.example/third');
    await expect(other.getByRole('button', { name: '收藏当前网页到 WebsiteStars' })).toBeVisible();
    const options = await context.newPage(); await options.goto(`${base}/options.html`);
    await options.locator('label').filter({ has: options.getByRole('switch', { name: '网页悬浮收藏按钮', exact: true }) }).click();
    await options.getByRole('button', { name: '保存设置', exact: true }).click();
    await expect(save).toHaveCount(0);
    await expect(other.getByRole('button', { name: '收藏当前网页到 WebsiteStars' })).toHaveCount(0);
    await page.reload(); await expect(save).toHaveCount(0);
    await options.reload();
    await expect(options.getByRole('switch', { name: '网页悬浮收藏按钮' })).not.toBeChecked();
    await options.locator('label').filter({ has: options.getByRole('switch', { name: '网页悬浮收藏按钮', exact: true }) }).click();
    await options.getByRole('button', { name: '保存设置', exact: true }).click();
    await expect(save).toBeVisible();
    await expect(other.getByRole('button', { name: '收藏当前网页到 WebsiteStars' })).toBeVisible();
    const sidebar = await context.newPage(); await sidebar.goto(`${base}/sidepanel.html`);
    await sidebar.setViewportSize({ width: 390, height: 844 });
    await expect(sidebar.locator('.item-list > li')).toHaveCount(2);
    await library.getByRole('button', { name: '查看详情：悬浮收藏测试文章' }).first().click();
    await library.getByRole('button', { name: '删除收藏', exact: true }).click();
    await library.getByRole('button', { name: '确认删除', exact: true }).click();
    await expect(sidebar.locator('.item-list > li')).toHaveCount(1);
    await page.goto('https://floating.example/article');
    await expect(save).not.toHaveAttribute('data-saved');
    await save.click(); await expect(sidebar.locator('.item-list > li')).toHaveCount(2);
    expect(errors).toEqual([]);
  } finally { await context.close(); await rm(profile, { recursive: true, force: true }); }
});
